sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t gjohncarter/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gjohncarter/react-test npm test

after_success:
  - docker build -t gjohncarter/fibo-client ./client
  - docker build -t gjohncarter/fibo-nginx ./nginx
  - docker build -t gjohncarter/fibo-server ./server
  - docker build -t gjohncarter/fibo-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push gjohncarter/fibo-client
  - docker push gjohncarter/fibo-nginx
  - docker push gjohncarter/fibo-server
  - docker push gjohncarter/fibo-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'fibo-docker'
  env: 'fiboDocker-env'
  bucket_name: 'elasticbeanstalk-us-west-2-968507404816'
  bucket_path: 'docker-fibo'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
